version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: futurisys_postgres
    environment:
      POSTGRES_USER: futurisys_user
      POSTGRES_PASSWORD: futurisys_password
      POSTGRES_DB: futurisys_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U futurisys_user -d futurisys_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
